buildscript {
    ext {
        agp_version = '9.3.1'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    tasks.configureEach { task ->
        if (task.name.toLowerCase().contains("lint")) {
            task.enabled = false
            task.onlyIf { false }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}