plugins {
    id 'com.android.library'
}

android {
    compileSdk 36

    defaultConfig {
        minSdk 23
        targetSdk 37
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        aidl true
        buildConfig true
    }
    namespace 'org.opencv'
    buildToolsVersion '37.0.0'
    ndkVersion '30.0.14904198'
    lint {
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
    compileSdkMinor 1
}

configurations.all {
    resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.3.21"
        force "org.jetbrains.kotlin:kotlin-stdlib:2.3.21"
    }
}