plugins {
    id 'com.android.library'
}

android {
    compileSdk 36

    defaultConfig {
        minSdk 21
        targetSdk 37
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        aidl true
        buildConfig true
    }
    namespace 'org.opencv'
    buildToolsVersion '37.0.0'
    ndkVersion "26.3.11579264"
    lint {
        targetSdk 36
        abortOnError false
        checkReleaseBuilds false
    }
    testOptions {
        targetSdk 36
    }
    compileSdkMinor 1
    compileSdkMinor 1
}

configurations.all {
    resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.4.0"
        force "org.jetbrains.kotlin:kotlin-stdlib:2.4.0"
    }
}